### ISSUE TITLE
Latency and streaming

### ISSUE THREAD

**Issue by karlbrowns** [kevinGodell/live-stream-media-source-extensions#4]
Hi,
I've changed the ffmpeg options to set frag_duration to 100000 and now latency is <1s, but not much less than that.

However, I've noticed that when I load the web page sometimes it doesn't pick up the stream.  Sometimes it plays it fine though.  Does the web player need to start at the beginning of a GOP?  If so, is there any way to force it to wait for a GOP start before playing?
Thanks,
Simon

**Comment by kevinGodell** [comment]
Sorry. I don't come to this repo anymore. The code is old and outdated. I have been meaning to archive it. It seems like the video player library is https://github.com/bilibili/flv.js and they have not had any activity since 2018. I suggest you check out some of my other repos that might give you better results in your experiment. 

- https://github.com/kevinGodell/mse-live-player
- https://github.com/kevinGodell/ffmpeg-streamer
